**Sauvegarde et chargement**

In [ ]:
import os
import numpy as np

# Sauvegarde l'état de la grille dans un fichier .txt.
def save_matrix(matrix, filename=None):
 #matrix: La matrice représentant l'état actuel de la grille.
 #filename: Le nom du fichier où sauvegarder la grille.
    if filename is None:
        filename = input("Entrez le nom de la sauvegarde: ") + ".txt"

    with open(filename, 'w') as f:
        for row in matrix:
            f.write(" ".join(map(str, row)) + "\n")
    print(f"Matrice sauvegardée dans {filename}")

grille = np.random.randint(2, size=(5, 5))  
save_matrix(grille, "sauvegarde.txt")


Matrice sauvegardée dans sauvegarde.txt


In [3]:
def load_matrix(filename):

    #Charge la matrice sauvegardé depuis le fichier texte.
    if not os.path.exists(filename):
        print(f"Erreur : Le fichier {filename} n'existe pas.")
        return None

    with open(filename, 'r') as f:
        lines = f.readlines()
        matrix = [list(map(int, line.split())) for line in lines]
    
    print(f"Matrice chargée depuis {filename}")
    return np.array(matrix)

matrice_chargee = load_matrix("sauvegarde.txt")
print("Matrice chargée :")
print(matrice_chargee)

Matrice chargée depuis sauvegarde.txt
Matrice chargée :
[[0 0 0 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 1 1 0]
 [1 0 0 1 0]]


In [ ]:
def list_saves():
    
   # Liste tous les fichiers de sauvegarde disponibles dans le répertoire actuel.
    
    saves = [f for f in os.listdir() if f.endswith(".txt")]
    if not saves:
        print("Aucune sauvegarde trouvée.")
    else:
        print("Sauvegardes disponibles :")
        for i, save in enumerate(saves, 1):
            print(f"{i}. {save}")
    return saves

# Liste les fichiers de sauvegarde
print("\nListe des sauvegardes disponibles :")
list_saves()


Liste des sauvegardes disponibles :
Sauvegardes disponibles :
1. sauvegarde.txt


['sauvegarde.txt']

In [ ]:
def select_save():
    
    #Permet à l'utilisateur de sélectionner une sauvegarde à charger.
    
    saves = list_saves()
    if not saves:
        return None

    choice = input("Entrez le numéro de la sauvegarde que vous souhaitez charger : ")
    try:
        choice_index = int(choice) - 1
        if 0 <= choice_index < len(saves):
            return saves[choice_index]
        else:
            print("Numéro invalide.")
            return None
    except ValueError:
        print("Entrée invalide.")
        return None

selection = select_save()



Sauvegardes disponibles :
1. sauvegarde.txt
